# -- Contents automatically generated by generate_classes.py on {{ generation_date.isoformat() }}
{% for import in imports -%}
{{ import }}
{% endfor %}
{% for class in classes %}
{{ class }}
{% endfor %}
